# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FastPointInspection
                                 A QGIS plugin
 Fast Point Inspection is a QGIS plugin that streamlines the process of classifying point geometries in a layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-27
        copyright            : (C) 2023 by Tharles de Sousa Andrade
        email                : irtharles@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FastPointInspection class from file FastPointInspection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fpi import FastPointInspection
    return FastPointInspection(iface)
